gem install discordrb
gem install similar_text
gem install stuff-classifier
gem install httparty
gem install satoshi-unit
gem install base32
gem install base58
gem install mechanize
gem install ecdsa
gem install openpgp
gem install iostreams
gem install metainspector
gem install core_extensions
